version: '{build}'

build: off

environment:
  matrix:
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

install:
  - ps: >-
      Add-Type -AssemblyName System.IO.Compression.FileSystem
          if (!(Test-Path -Path "C:\maven" )) {
            (new-object System.Net.WebClient).DownloadFile(
              'http://www.us.apache.org/dist/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.zip',
              'C:\maven-bin.zip'
            )

            [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
          }
  - ps: >-
      Add-Type -AssemblyName System.IO.Compression.FileSystem
          if (!(Test-Path -Path "C:\ant" )) {
            (new-object System.Net.WebClient).DownloadFile(
              'http://www.us.apache.org/dist/ant/binaries/apache-ant-1.9.7-bin.zip',
              'C:\ant-bin.zip'
            )

            [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\ant-bin.zip", "C:\ant")
          }
  - cmd: SET PATH=C:\maven\apache-maven-3.3.3\bin;C:\ant\apache-ant-1.9.7\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: echo %PATH%
  - cmd: java -version

cache:
  - C:\maven
  - C:\Users\appveyor\.m2

test_script:
  - mvn -Ptest
  - ant test:mri:appveyor
