language: ruby
script:
  - bundle exec rspec
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.1
  - ruby-head
  - rbx-2
  - jruby-1.7
  - jruby-head
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-1.7
    - rvm: jruby-head
